# Generated by Django 5.1.4 on 2025-04-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_paymenttransaction_delete_payments'),
        ('wallflower', '0002_customer_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallflower.product'),
        ),
    ]
