# Generated by Django 5.1.4 on 2025-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_paymenttransaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
