# Generated by Django 5.2 on 2025-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_paymenttransaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='cart_data',
            field=models.JSONField(default=list),
        ),
    ]
